## 实验：创建 NumPy 数组

### 本地环境配置

In [1]:
from matplotlib import pyplot as plt
%matplotlib inline
plt.rcParams['font.family'] = 'sans-serif'    # 用来正常显示中文
plt.rcParams['font.sans-serif'] = 'SimHei'
plt.rcParams['axes.unicode_minus'] = False   # 设置正常显示符号

# 设置输入输出路径
import os
base_path = os.environ.get("BASE_PATH",'../data/')
data_path = os.path.join(base_path + "lab1/")
result_path = "result/"
os.makedirs(result_path, exist_ok=True)

# 忽略第三方支援库更新兼容性提示
import warnings
warnings.simplefilter('ignore') 

### 指令格式

我想你作为一个数据分析师，帮我创建一个 NumPy 数组，数组形状为 **<font color="#0000dd">( x, y, z )</font>**，请在 **<font color="#0000dd">[ i 到 j ]</font>** 之间随机生成数组初始值，并将其输出

### 指令示例

我想你作为一个数据分析师，帮我创建一个 NumPy 数组，数组形状为 **( 3, 4, 10 )**，请在 **[ 1 到 10 ]** 之间随机生成数组初始值，并将其输出

<img src="./img/12.png" width=80%>

### ChatGPT 代码测试

In [2]:
import numpy as np

# 创建一个形状为 (3, 4, 10) 的数组
array = np.random.randint(1, 11, size=(3, 4, 10))

# 输出数组
print(array)

[[[ 5  8  2  5  9  5  1  2  2  5]
  [10  1  5  8  8  9  1 10  1  7]
  [ 1  8  6  2  6  2  4  8 10 10]
  [ 3  8  3  9  7  8 10  2  6  5]]

 [[ 5  6  7  7  9 10  8  3  6 10]
  [ 9  6  8  2  1  5 10  2  6  8]
  [ 5  9  3 10  1  7  8  3 10 10]
  [ 1  6  6  7  8  9  3  2  9  6]]

 [[ 2  2  3  1  3  8 10  8  9  6]
  [ 5  3 10  1  4  2  7  3  6 10]
  [ 5  4  5  4  2  6  8 10  2  5]
  [ 8  7  4  9  8  2  7  3  4  1]]]
